//  imporitng core node modules
var express=require('express')
var app = express()
var bp = require('body-parser')
var device = require('express-device')
var cookie = require('cookie')

//importing routes
var authentication = require('./routes/authentication.js')
var login = require('./routes/login')
var faculty = require('./routes/faculty')
var admin = require('./routes/admin')
var batch = require('./routes/batch')
var customscore = require('./routes/customscore.js')
var sendsms = require('./routes/sendsms')
var download = require('./routes/download')
var errorRecorder = require('./routes/era')

app.set('views','./views')
app.set('view engine','ejs')
app.use(device.capture())
app.use(authentication)
app.use('/',bp.json(),login)
app.use('/sendsms',bp.json(),sendsms)
app.use('/admin',bp.json(),admin)
app.use('/custom-testscore',bp.json(),customscore)
app.use('/faculty',bp.json(),faculty)
app.use('/student',bp.json(),batch)
app.use('/download',download)
app.use('/error',bp.json(),errorRecorder)
app.get('/logout',function(req,res){
  console.log('logout')
  res.setHeader('Set-cookie',cookie.serialize('user','',{expires: new Date(1),httpOnly:true}))
  res.status(200)
  res.end()
})

app.use(express.static('public'))
app.use('/login',express.static('public'))
app.use('/login/faculty',express.static('public'))
app.use('/login/admin',express.static('public'))

app.listen(process.env.PORT || 80,function(){
  console.log("listening on port 80")
})
